import os
import pickle
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from allosaurus.app import read_recognizer


def load_converted_metadata(metadata_csv: str) -> pd.DataFrame:
    """
    Loads the metadata CSV (source / target / converted) generated by SeedVC.
    """
    if not os.path.exists(metadata_csv):
        raise FileNotFoundError(f"{metadata_csv} not found.")

    return pd.read_csv(metadata_csv, sep="\t", encoding="utf-8")


def generate_phoneme_sequences(seedvc_metadata_csv: str, output_dir: str = "outputs/phonemes") -> None:
    """
    """
    os.makedirs(output_dir, exist_ok=True)

    df_meta = load_converted_metadata(seedvc_metadata_csv)

    model = read_recognizer(inference_config_or_name='latest', alt_model_path=None)

    for _, row in tqdm(df_meta.iterrows(), total=len(df_meta), desc="Extracting phonemes"):

        row = dict(row)


        # source	target	converted

        phonemes = model.recognize(
            filename=row['source'],
            lang_id="ipa",
            topk=1,
            emit=1.2,
            timestamp=False
 

        )

        print(phonemes)

        break;


def prepare_phoneme_sequences(seedvc_metadata_csv: str = "outputs/seedvc-metadata.csv", 
                              output_dir: str = "outputs/phonemes") -> None:
    """
    
    """
    generate_phoneme_sequences(seedvc_metadata_csv, output_dir)
